x<-1:50
w<-1+sqrt(x)/2
example <-data.frame(x=x, y= x + rnorm(x)*w)
attach(example1)
example1 <-data.frame(x=x, y= x + rnorm(x)*w)
> attach(example1)
x<-1:50
w<-1+sqrt(x)/2
example1<-data.frame(x=x, y= x + rnorm(x)*w)
attach(examle)
attach(example1)
x <- 1:50
w <- 1 + sqrt(x)/2
example1 <- data.frame(x=x, y= x + rnorm(x)*w)
attach(example1)
x <- 1:50
w <- 1 + sqrt(x)/2
example1 <- data.frame(x=x, y= x + rnorm(x)*w)
attach(example1)
attach(example1)
attach(example1)
x<-1:50
w<-1+sqrt(x)/2
example1<-data.frame(x=x, y= x + rnorm(x)*w)
attach(example1)
fm<-lm(y ~ x)
summary(fm)
lrf<-lowest(x, y)
plot(x, y)
lines(x, lrf$y)
lines(x, 1rf$y)
abines(0, 1, 1ty=3)
abline(0, 1, 1ty=3)
x <- 1:50
w <- 1 + sqrt(x)/2
example1 <- data.frame(x=x, y= x + rnorm(x)*w)
attach(example1)
fm <- lm(y ~ x)
summary(fm)
lrf <- lowess(x, y)
plot(x, y)
lines(x, lrf$y)
abline(0, 1, lty=3)
abline(coef(fm))
detach()
load("C:/Users/Owner/Desktop/Psychology/R-work/V0500_Lecture1/BRFSS2022/BRFSS2022_rev.RData")
load("BRFSS2022_rev.RData")
load("C:/Users/Owner/Desktop/Psychology/R-work/V0500_Lecture1/BRFSS2022/.RData")
load("BRFSS2022_rev.RData")
x <- 1:50
w <- 1 + sqrt(x)/2
example1 <- data.frame(x=x, y= x + rnorm(x)*w)
attach(example1)
fm <- lm(y ~ x)
summary(fm)
lrf <- lowess(x, y)
plot(x, y)
lines(x, lrf$y)
abline(0, 1, lty=3)
abline(coef(fm))
detach()
load("C:/Users/Owner/Desktop/Psychology/R-work/V0500_Lecture1/BRFSS2022/BRFSS2022_rev.RData")
load("BRFSS2022_rev.RData")
load("C:/Users/Owner/Desktop/Psychology/R-work/V0500_Lecture1/BRFSS2022/BRFSS2022_rev.RData")
#glimpse(brfss22) try this later
brfss22[1:10,1:6]
attach(brfss22)
summary(sleptim1[x-state == "new york"])
summary(SLEPTIM1[X_STATE == "New York"])
summary(SLEPTIM1[X_STATE == "Ohio"])
mean(SLEPTIM1[X_STATE == "New York"], na.rm = TRUE)
sd(SLEPTIM1[X_STATE == "New York"], na.rm = TRUE)
mean(SLEPTIM1[X_STATE == "Ohio"], na.rm = TRUE)
sd(SLEPTIM1[X_STATE == "Ohio"], na.rm = TRUE)
hist(SLEPTIM1[(SLEPTIM1 >5) & (SLEPTIM1 < 9)])
summary(SEXVAR)
summary(BIRTHSEX)
summary(GENHLTH)
summary(EDUCA)
install.packages("tidyverse")
install.packages("plyr")
library(plyr)
library(tidyverse)
summary(X_AGEG5YR)
summary(INCOME3)
ddply(brfss22, .(INCOME3), summarize, mean = round(mean(SLEPTIM1, na.rm = TRUE), 2), sd = round(sd(SLEPTIM1, na.rm = TRUE), 2), n_obsv = length(is.na(SLEPTIM1) == FALSE) )
ddply(brfss22, .(INCOME3), summarize, sleep90th = quantile(SLEPTIM1,probs = 0.9, na.rm = TRUE), sleep10th = quantile(SLEPTIM1,probs = 0.1, na.rm = TRUE), n_obs = length(is.na(SLEPTIM1) == FALSE) )
table(GENHLTH,SEXVAR)
xtabs(~GENHLTH + SEXVAR)
prop.table(table(GENHLTH,SEXVAR))
x <- 1:50
w <- 1 + sqrt(x)/2
example1 <- data.frame(x=x, y= x + rnorm(x)*w)
attach(example1)
fm <- lm(y ~ x)
summary(fm)
lrf <- lowess(x, y)
plot(x, y)
lines(x, lrf$y)
abline(0, 1, lty=3)
abline(coef(fm))
detach()
View(brfss22)
View(brfss22)
View(brfss22)
load("C:\Users\Owner\Desktop\Psychology\R-work\V0500_Lecture1/BRFSS2022_rev.RData")
load("C:\Users\Owner\Desktop\Psychology\R-work\V0500_Lecture1/BRFSS2022_rev.RData")
x <- 1:50
w <- 1 + sqrt(x)/2
example1 <- data.frame(x=x, y= x + rnorm(x)*w)
attach(example1)
fm <- lm(y ~ x)
summary(fm)
lrf <- lowess(x, y)
plot(x, y)
lines(x, lrf$y)
abline(0, 1, lty=3)
abline(coef(fm))
detach()
load("C:/Users/Owner/Desktop/Psychology/R-work/V0500_Lecture1/BRFSS2022/BRFSS2022_rev.RData")
load("BRFSS2022_rev.RData")
load("BRFSS2022_rev.RData")
x <- 1:50
w <- 1 + sqrt(x)/2
example1 <- data.frame(x=x, y= x + rnorm(x)*w)
attach(example1)
fm <- lm(y ~ x)
summary(fm)
lrf <- lowess(x, y)
plot(x, y)
lines(x, lrf$y)
abline(0, 1, lty=3)
abline(coef(fm))
detach()
load("C:/Users/Owner/Desktop/Psychology/R-work/V0500_Lecture1/BRFSS2022/BRFSS2022_rev.RData")
#glimpse(brfss22) try this later
brfss22[1:10,1:6]
attach(brfss22)
summary(brfss22)
summary(SLEPTIM1[X_STATE == "New York"])
summary(SLEPTIM1[X_STATE == "Ohio"])
mean(SLEPTIM1[X_STATE == "New York"], na.rm = TRUE)
sd(SLEPTIM1[X_STATE == "New York"], na.rm = TRUE)
mean(SLEPTIM1[X_STATE == "Ohio"], na.rm = TRUE)
sd(SLEPTIM1[X_STATE == "Ohio"], na.rm = TRUE)
hist(SLEPTIM1[(SLEPTIM1 >5) & (SLEPTIM1 < 9)])
summary(SEXVAR)
summary(BIRTHSEX)
summary(GENHLTH)
summary(EDUCA)
install.packages("tidyverse")
install.packages("plyr")
summary(X_AGEG5YR)
summary(INCOME3)
ddply(brfss22, .(INCOME3), summarize, mean = round(mean(SLEPTIM1, na.rm = TRUE), 2), sd = round(sd(SLEPTIM1, na.rm = TRUE), 2), n_obsv = length(is.na(SLEPTIM1) == FALSE) )
ddply(brfss22, .(INCOME3), summarize, sleep90th = quantile(SLEPTIM1,probs = 0.9, na.rm = TRUE), sleep10th = quantile(SLEPTIM1,probs = 0.1, na.rm = TRUE), n_obs = length(is.na(SLEPTIM1) == FALSE) )
table(GENHLTH,SEXVAR)
xtabs(~GENHLTH + SEXVAR)
prop.table(table(GENHLTH,SEXVAR))
One interesting finding is that, there seems to be a slight increase in sleep duration as income increases
I find it surprising that the dataset, though looks concise, contains vast information that can significantly enhance our understanding of the topic and its practical usability.